virtual_modifiers:
  - CapsLock
keymap:
  - remap:
      CapsLock-h: Left
      CapsLock-j: Down
      CapsLock-k: Up
      CapsLock-l: Right
      CapsLock-u: Home
      CapsLock-o: End
      CapsLock-apostrophe: Delete
      CapsLock-p: Print
