import = ["/Users/astsu/.config/alacritty/themes/gruvbox_light.toml"]

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 8
y = 8
